health_search/eHealth/urls.py
from django.conf.urls import patterns, url
from health_search.settings import STATIC_PATH
from eHealth import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^about/$', views.about, name='about'),
                       url(r'^search/$', views.search, name='search'),
                       url(r'^user/', views.user, name='user'),
                       url(r'^register/', views.register, name='register'),
                       url(r'^add_category/$', views.add_category, name='add_category'),
                       url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
                       url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
                       url(r'^public_categories/$', views.public_categories, name='public_categories'),
                       url(r'^goto/$', views.track_url, name='goto'),
                       #url(r'^update_username/$', views.update_username, name='update_username'),
                       url(r'^update_email/$', views.update_email, name='update_email'),
                       url(r'^update_password/$', views.update_password, name='update_password'),
                       url(r'^update_picture/$', views.update_picture, name='update_picture'),
                       #url(r'^user/(?P<user_name>[\w\-]+)/$', views.user, name='user'),
                       url(r'^category_search/$', views.category_search, name='category_search'),
                       )

from django.conf import settings

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

health_search/health_search/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/'

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'health_search.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^', include('eHealth.urls')),
                       url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
                       url(r'^accounts/', include('registration.backends.simple.urls')),
                       )

health_search/eHealth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from scores.scores import get_all_scores

class UserProfile(models.Model):
    def picname(self, *args, **kwargs):
        username = self.user.get_username()
        print username
        return 'profile_images/'+username

    gender_choices=(('male','Male',),('female','Female',))
    user = models.OneToOneField(User)
    picture = models.ImageField(upload_to=picname, blank=True)
    dateOfBirth = models.DateField()
    gender = models.CharField(max_length=6,choices=gender_choices)


    def __unicode__(self):
        return self.user.username




class Category(models.Model):
    user = models.ForeignKey(UserProfile)
    name = models.CharField(max_length=128)
    views = models.IntegerField(default=0)
    slug = models.SlugField()
    public = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.slug = self.user.user.username +slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def change_public(self, makepublic):
        self.public=makepublic

    def __unicode__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    summary = models.CharField(max_length=1000)
    flesch_score = models.IntegerField(default=0)
    polarity_score = models.IntegerField(default=0)
    subjectivity_score = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        super(Page, self).save(*args, **kwargs)


    def get_scores(self):
        self.save()
        #save so if scores has an error the page is still saved
        page_scores=get_all_scores(self.url)
        self.flesch_score       = page_scores[0]
        self.polarity_score     = page_scores[1]
        self.subjectivity_score = page_scores[2]
        self.save()

    def __unicode__(self):
        return self.title

# Create your models here.

health_search/eHealth/views.py
import os
from django.shortcuts import render, HttpResponseRedirect,redirect
from health_search.settings import MEDIA_ROOT
from search.federated_search import federated_run_querys
from eHealth.forms import UserForm, UserProfileForm, PageForm, CategoryForm, UserEditNameForm, UserEditEmailForm, \
    UserEditPasswordForm, UserEditPictureForm
from eHealth.models import Category, Page, UserProfile
from django.contrib.auth import authenticate, login
import json
from django.core.context_processors import request
from django.contrib.auth.models import User
from django.template import RequestContext


def default_context(request, dict):
    try:
        category_list = Category.objects.filter(public=True).order_by('-views')[:20]
        default = {'topcategories': category_list}
        default.update(dict)
        return default
    except:
        default = {}
        default.update(dict)
        return default


def index(request):
    categories = Category.objects.filter(public=True)
    return render(request, 'eHealth/index.html', default_context(request, {'categories': categories}))


def about(request):
    return render(request, 'eHealth/about.html', default_context(request, {}))


def search(request):
    result_list = {'federated_results': [],
                   'bing_results': [],
                   'healthFinder_results': [],
                   'medlinePlus_results': [],
                   }


    if request.method == 'POST':
        query = request.POST['query'].strip()

        if query:
            result_list = federated_run_querys(request, query)

    try:
        username = None
        if request.user.is_authenticated():
            username = UserProfile.objects.filter(user=request.user).get()
        category_list = Category.objects.filter(user=username)
        dict = {'user_categories': category_list}
        result_list.update(dict)
    except:
        pass

    return render(request, 'eHealth/search.html', default_context(request, result_list))


def user(request):
    context_dict = {}
    try:
        user = UserProfile.objects.filter(user=request.user).get()
        context_dict['username'] = request.user.get_username()
        context_dict['email'] = request.user.email
        context_dict['dob'] = user.dateOfBirth
        context_dict['gender'] = user.gender
        context_dict['all_categories'] = Category.objects.filter(user=user)
    except:
        print 'user profile error:',
        return HttpResponseRedirect('/')
    response = render(request, 'eHealth/user.html', default_context(request, context_dict))
    return response

"""
def update_username(request):
    ## Allows the user to change supplied info

    if request.method == 'POST':
        form = UserEditNameForm(request.POST, instance=request.user)
        ## If form is valid, redirect them to their profile page
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/user/')
    else:
        form = UserEditNameForm()
    context_dict = {'form_name': 'Change username',
                    'url':'update_username',
                    'form':form,
                    }

    return render(request, 'eHealth/update_user.html', default_context(request,context_dict))
"""


def update_email(request):
    ## Allows the user to change supplied info

    if request.method == 'POST':
        form = UserEditEmailForm(request.POST, instance=request.user)
        ## If form is valid, redirect them to their profile page
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/user/')
    else:
        form = UserEditEmailForm()
    context_dict = {'form_name': 'Change Email',
                    'url':'update_email',
                    'form':form,
                    }

    return render(request, 'eHealth/update_user.html', default_context(request,context_dict))

def update_password(request):
    ## Allows the user to change supplied info

    if request.method == 'POST':
        form = UserEditPasswordForm(request.POST, instance=request.user)
        ## If form is valid, redirect them to their profile page
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/user/')
    else:
        form = UserEditPasswordForm()
    context_dict = {'form_name': 'Change Password',
                    'url':'update_password',
                    'form':form,
                    }

    return render(request, 'eHealth/update_user.html', default_context(request,context_dict))


def update_picture(request):
    ## Allows the user to change supplied info

    if request.method == 'POST':
        form = UserEditPictureForm(request.POST, instance=request.user)
        ## If form is valid, redirect them to their profile page
        if form.is_valid():
            profile=form.save(commit=False)
            user=UserProfile.objects.get(user=profile)
            try:
                os.remove(os.path.join(MEDIA_ROOT,'profile_images',user.user.get_username()))
            except:
                pass
            if 'picture' in request.FILES:
                user.picture = request.FILES['picture']
            user.save()
            profile.save()
            return HttpResponseRedirect('/user/')
    else:
        form = UserEditPictureForm()
    context_dict = {'form_name': 'Change Picture',
                    'url':'update_picture',
                    'form':form,
                    }

    return render(request, 'eHealth/update_user.html', default_context(request,context_dict))






def register(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')

    if request.method == 'POST':

        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            new_user = authenticate(username=request.POST['username'],
                                    password=request.POST['password'],
                                    )
            login(request, new_user)
            return HttpResponseRedirect('/')

        else:
            print user_form.errors, profile_form.errors

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,
                  'registration/register.html',
                  default_context(request, {'user_form': user_form, 'profile_form': profile_form, }))


def category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        context_dict['category_name'] = category.name
        context_dict['category_name_slug'] = category.slug
        context_dict['category_views'] = category.views
        context_dict['pages']=Page.objects.filter(category=category)
        context_dict['owner']=category.user.user.username
        if request.POST:
            public = request.POST.get('public')
            category.public = (str(public)=='True')
            category.save()
        context_dict['public'] = category.public
        try:
            if str(request.user) == str(category.user):
                context_dict['is_owner'] = True
            else:
                context_dict['is_owner'] = False
        except:
            context_dict['is_owner'] = False

        #if you are not aurthrised to view a page you are returned to index
        if not (context_dict['is_owner'] or context_dict['public']):
            return HttpResponseRedirect('/')

    except Category.DoesNotExist:
        pass

    return render(request, 'eHealth/category.html', default_context(request, context_dict))


def add_page(request, category_name_slug):
    try:
        cat = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        cat = None
    print cat
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if cat:
                page = form.save(commit=False)
                page.category = cat
                page.views = 0
                page.get_scores()
                return HttpResponseRedirect('/category/'+category_name_slug)
        else:
            print form.errors
    else:
        form = PageForm()

    context_dict = {'form': form, 'category': cat}

    return render(request, 'eHealth/add_page.html', default_context(request, context_dict))


def add_category(request):
    try:
        user = UserProfile.objects.get(user=request.user)
    except:
        user = None
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            if user:
                cat = form.save(commit=False)
                cat.user = user
                cat.save()
                return HttpResponseRedirect('/user')

        else:
            print form.errors
    else:
        form = CategoryForm()
    return render(request, 'eHealth/add_category.html', default_context(request, {'form': form}))


def track_url(request):
    page_id = None
    url = '/'
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            try:
                page = Page.objects.get(id=page_id)
                page.views = page.views + 1
                page.save()
                category = page.category
                category.views = category.views +1
                category.save()
                url = page.url
            except:
                pass

    return redirect(url)


def public_categories(request):
    categories = Category.objects.filter(public=True).order_by('-views')[:10]

health_search/templates/eHealth/about.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}About{% endblock %}

{% block body_block %}
    <div class="page-header">
        <h1>About eHealth</h1>
    </div>
    <div>
        <h3>What is eHealth?</h3>

        <p> The purpose of this application is to help people find out about particular conditions and to save the
            information that they find into different folders. The application lets people search across two different
            medical
            sites (medline and healthfinder) and the general web (bing). People using the application would like to
            self-diagnose,
            i.e. given some symptoms find out what are the likely conditions. They would also like to find out
            information about
            particular conditions, treatments and medicines.</p>

        <h3>API's used</h3>
        <ul>
            <li><a href="http://healthfinder.gov/developer/How_to_Use.aspx">Healthfinder</a></li>
            <li><a href="https://www.nlm.nih.gov/medlineplus/webservices.html">MedlinPlus</a></li>
            <li><a href="https://datamarket.azure.com/dataset/bing/search">Bing</a></li>
        </ul>
        <h3>Made By</h3>
        <ul>
            <li>Kevin</li>
            <li>Duy Hieu</li>
            <li>Philippe</li>
            <li>Christopher</li>
        </ul>
    </div>
{% endblock %}

health_search/templates/eHealth/add_category.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Add Category{% endblock %}


{% block body_block %}

    <form role="form" id="category_form" method="post" action="/add_category/">
        <h2 class="form-signing-heading">Add a Category</h2>
        </br>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        </br></br>
        <button class="btn btn-primary" type="submit" name="submit">Add Category</button>
    </form>

{% endblock %}

health_search/templates/eHealth/add_page.html
{% extends 'base.html' %}

{% block title %}Add Page{% endblock %}


{% block body_block %}
    {% if category %}

        <form role="form" id="page_form" method="post" action="/category/{{ category.slug }}/add_page/">
            <h2 class="form-signin-heading">Add a Page to <a
                    href="/category/{{ category.slug }}/"> {{ category.name }}</a></h2>
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br/>
                {{ field }}<br/>
            {% endfor %}

            <br/>
            <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
        </form>
    {% else %}
        <p>This category does not exist.</p>
    {% endif %}


{% endblock %}

health_search/templates/eHealth/search.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Search{% endblock %}

{% block body_block %}
    <div class="page-header">
        <h1> Search Results</h1>
    </div>
    <div>

        <div class="panel">


            <div class="tabs">
                <ul class="tab-links">
                    <li class="active"><a href="#tab1">Federated Search</a></li>
                    <li><a href="#tab2">Bing Search</a></li>
                    <li><a href="#tab3">Healthfinder Search</a></li>
                    <li><a href="#tab4">Medlineplus Search</a></li>
                </ul>

                <div class="tab-content">
                    <div id="tab1" class="tab active">
                        {% if federated_results %}
                            <div class="panel-heading">

                                <div class="panel-body">
                                    <div class="list-group">
                                        {% for result in federated_results %}
                                            <div class="list-group-item">
                                                <h4 class="list-group-item-heading"><a
                                                        href="{{ result.link }}">{{ result.title }}</a></h4>

                                                <p class="list-group-item-text">{{ result.summary }}</p>

                                                <p class="list-group-item-text">{{ result.from }}</p>

                                                {% if user.is_authenticated %}
                                                    <button class="btn btn-default dropdown-toggle search" type="button" id="menu1" data-toggle="dropdown" >Add to category
                                                    <span class="caret"></span></button>
                                                    <ul class="dropdown-menu search" role="menu" aria-labelledby="menu1">
                                                        {% for category in user_categories %}
                                                            <form role="form" method="post" action="/category/{{ category.slug }}/add_page/">
                                                                {% csrf_token %}
                                                                <input id="id_views" name="views" type="hidden" value="0" />
                                                                <input id="id_title" maxlength="128" type="hidden" name="title" value="{{result.title}}" />
                                                                <input id="id_url" maxlength="200" type="hidden" name="url" value="{{result.link}}" />
                                                                <input id="id_summary" maxlength="1000" type="hidden" name="summary" value="{{result.summary}}" />
                                                                <li role="presentation">
                                                                    <button class="menuitem" type="submit button" id="id_category" name="category" value="{{ category }}" >{{ category.name }}</button>
                                                                </li>
                                                            </form>
                                                        {% endfor %}
                                                    </ul>
                                                {% endif %}
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>

                    <div id="tab2" class="tab">
                        {% if bing_results %}
                            <div class="panel-heading">

                                <div class="panel-body">
                                    <div class="list-group">
                                        {% for result in bing_results %}
                                            <div class="list-group-item">
                                                <h4 class="list-group-item-heading"><a
                                                        href="{{ result.link }}">{{ result.title }}</a></h4>

                                                <p class="list-group-item-text">{{ result.summary }}</p>

                                                <p class="list-group-item-text">{{ result.from }}</p>

                                            {% if user.is_authenticated %}
                                                    <button class="btn btn-default dropdown-toggle search" type="button" id="menu1" data-toggle="dropdown" >Add to category
                                                    <span class="caret"></span></button>
                                                    <ul class="dropdown-menu search" role="menu" aria-labelledby="menu1">
                                                        {% for category in user_categories %}
                                                            <form role="form" method="post" action="/category/{{ category.slug }}/add_page/">
                                                                {% csrf_token %}
                                                                <input id="id_views" name="views" type="hidden" value="0" />
                                                                <input id="id_title" maxlength="128" type="hidden" name="title" value="{{result.title}}" />
                                                                <input id="id_url" maxlength="200" type="hidden" name="url" value="{{result.link}}" />
                                                                <input id="id_summary" maxlength="1000" type="hidden" name="summary" value="{{result.summary}}" />
                                                                <li role="presentation">
                                                                    <button class="menuitem" type="submit button" id="id_category" name="category" value="{{ category }}" >{{ category.name }}</button>
                                                                </li>
                                                            </form>
                                                        {% endfor %}
                                                    </ul>
                                                {% endif %}
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>

                        {% endif %}
                    </div>

                    <div id="tab3" class="tab">
                        {% if healthFinder_results %}
                            <div class="panel-heading">

                                <div class="panel-body">
                                    <div class="list-group">
                                        {% for result in healthFinder_results %}
                                            <div class="list-group-item">
                                                <h4 class="list-group-item-heading"><a
                                                        href="{{ result.link }}">{{ result.title }}</a></h4>

                                                <p class="list-group-item-text">{{ result.summary }}</p>

                                                <p class="list-group-item-text">{{ result.from }}</p>

                                            {% if user.is_authenticated %}
                                                    <button class="btn btn-default dropdown-toggle search" type="button" id="menu1" data-toggle="dropdown" >Add to category
                                                    <span class="caret"></span></button>
                                                    <ul class="dropdown-menu search" role="menu" aria-labelledby="menu1">
                                                        {% for category in user_categories %}
                                                            <form role="form" method="post" action="/category/{{ category.slug }}/add_page/">
                                                                {% csrf_token %}
                                                                <input id="id_views" name="views" type="hidden" value="0" />
                                                                <input id="id_title" maxlength="128" type="hidden" name="title" value="{{result.title}}" />
                                                                <input id="id_url" maxlength="200" type="hidden" name="url" value="{{result.link}}" />
                                                                <input id="id_summary" maxlength="1000" type="hidden" name="summary" value="{{result.summary}}" />
                                                                <li role="presentation">
                                                                    <button class="menuitem" type="submit button" id="id_category" name="category" value="{{ category }}" >{{ category.name }}</button>
                                                                </li>
                                                            </form>
                                                        {% endfor %}
                                                    </ul>
                                                {% endif %}
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>

                        {% endif %}
                    </div>

                    <div id="tab4" class="tab">
                        {% if medlinePlus_results %}
                            <div class="panel-heading">

                                <div class="panel-body">
                                    <div class="list-group">
                                        {% for result in medlinePlus_results %}
                                            <div class="list-group-item">
                                                <h4 class="list-group-item-heading"><a
                                                        href="{{ result.link }}">{{ result.title }}</a></h4>

                                                <p class="list-group-item-text">{{ result.summary }}</p>

                                                <p class="list-group-item-text">{{ result.from }}</p>

                                            {% if user.is_authenticated %}
                                                    <button class="btn btn-default dropdown-toggle search" type="button" id="menu1" data-toggle="dropdown" >Add to category
                                                    <span class="caret"></span></button>
                                                    <ul class="dropdown-menu search" role="menu" aria-labelledby="menu1">
                                                        {% for category in user_categories %}
                                                            <form role="form" method="post" action="/category/{{ category.slug }}/add_page/">
                                                                {% csrf_token %}
                                                                <input id="id_views" name="views" type="hidden" value="0" />
                                                                <input id="id_title" maxlength="128" type="hidden" name="title" value="{{result.title}}" />
                                                                <input id="id_url" maxlength="200" type="hidden" name="url" value="{{result.link}}" />
                                                                <input id="id_summary" maxlength="1000" type="hidden" name="summary" value="{{result.summary}}" />
                                                                <li role="presentation">
                                                                    <button class="menuitem" type="submit button" id="id_category" name="category" value="{{ category }}" >{{ category.name }}</button>
                                                                </li>
                                                            </form>
                                                        {% endfor %}
                                                    </ul>
                                                {% endif %}
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>

                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

health_search/templates/eHealth/update_user.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block body_block %}
    <h1>{{ form_name }}</h1>
    <form id="{{ form.auto_id }}" method="POST" action="{% url url %}" enctype="multipart/form-data">
        {% csrf_token %}

        <table>
            <tbody>
            {{ form.as_table }}
            <tr>
                <th></th>
                <td>
                    <button type="submit" class="btn btn-default">Update</button>
                </td>
            </tr>

            </tbody>

        </table>
    </form>
{% endblock %}